name: Release Package

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release-mongo-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Read version from version.txt
        id: version
        run: |
          cd mongo
          echo "version=$(cat version.txt)" >> $GITHUB_OUTPUT

      - name: Create tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag mongo/v${{ steps.version.outputs.version }}
          git push origin mongo/v${{ steps.version.outputs.version }}
          echo "Tag created: mongo/v${{ steps.version.outputs.version }}"
